easy_admin:
    design:
        brand_color: 'black'
    site_name: '<img src="/build/images/BrandHorizontalBlack.png" height="35"> ____Manager'
    user:
        name_property_path: email # affichage en haut à droite de l'admin une fois la partie register faite
    entities:
        Utilisateurs:
            class: App\Entity\User
#            form:
#                fields:
#                    - firstname
#                    - lastname
#                    - email
#                    - address
#                    - town
#                    - zipcode
#                    - country
#                    - phone_number
#                    - { property: 'birthday', type: 'birthday', label: 'Date de naissance' }
#                    - roles
#                    - plainPassword
        Montres:
            class: App\Entity\WatchModel
        Références:
            class: App\Entity\WatchEntity
        Locations:
            class: App\Entity\Location
        Transporteurs:
            class: App\Entity\DeliveryCompany
         
                

