easy_admin:
    design:
        brand_color: 'black'
    site_name: '<img src="/build/images/BrandHorizontalBlack.png" height="35"> ____Manager'
    user:
        name_property_path: email # affichage en haut à droite de l'admin une fois la partie register faite
    entities:
        Utilisateurs:
            class: App\Entity\User
            form:
                fields: 
                    - { property: firstname, label: 'Prénom' }
                    - { property: lastname, label: 'Nom' }                    
                    - email
                    - { property: gender, label: 'Genre', type: choice, type_options: {choices: { 'femme' : '0', 'homme' : '1'}} }
                    - { property: address, label: 'Adresse' }
                    - { property: town, label: 'Ville' }
                    - { property: zipcode, label: 'Code Postal' }
                    - { property: country, label: 'Pays' }
                    - { property: phone_number, label: 'Téléphone' }
                    - { property: 'birthday', type: 'birthday', label: 'Date de Naissance' }
                    - roles
#                    - { property: password, type: 'password', label: 'Mot de passe' }
                    
                new:
                    fields:
                        - { property: plainPassword, type: 'password', label: 'Mot de passe' }

        Montres:
            class: App\Entity\WatchModel
            form:
                fields:
                    - { property: brand, label: 'Marque' }
                    - { property: model, label: 'Modèle' }
                    - { property: gender, label: 'Genre', type: choice, type_options: {choices: { 'femme' : '0', 'homme' : '1', 'unisex' : '2'}} }
                    - { property: description, label: 'Description' }
                    - { property: color, label: 'Couleur' }
                    - { property: price, label: 'Prix' }
                    - { property: glass, label: 'Verre' }                    
                    - { property: movement, label: 'Mouvement' }
                    - { property: diameter, label: 'Diamètre' }
                    - { property: waterproof, label: 'Étanchéité' }
#                    - { property: glass, label: 'vitre' }
                    - { property: function, label: 'Fonction' }
                    - { property: watch_clasps, label: 'Fermoir' }
                    - Bracelet
                    - { property: watch_dial, label: 'Cadran' }
                    - { property: deposit, label: 'Dépôt' }
                    - { property: pictures, type: 'collection', type_options: { entry_type: App\Form\PicturesType, allow_delete: true } }
                    - { property: watchEntities, label: 'Numéro de Série', type: 'collection', type_options: { entry_type: App\Form\EntityType } }

        Locations:
            class: App\Entity\Location
            disabled_actions: ['new']            

        Transporteurs:
            class: App\Entity\DeliveryCompany
            form:
                fields:
                    - { property: name, label: 'Nom' }
                    - { property: logo, label: 'Logo', type: file_upload, type_options: { upload_dir: 'public/uploads' } }
                    
                    - { property: tracking_link, label: 'Suivi de commande' }
                

