easy_admin:
    site_name: '<img src="/build/images/BrandHorizontalBlack.png" height="35"> ____Manager'
    entities:
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
        - App\Entity\WatchModel

