easy_admin:
    design:
        menu:
            - { label: 'Accueil du site', icon: 'home',  route: 'homepage' }
           
            - { entity: Utilisateurs, icon: "users" }
            - { entity: Montres, icon: "clock" }
            - { entity: Numéro_de_série, icon: "tags" }
            - { entity: Location, icon: "tags" }
            - { entity: Transporteurs, icon: "truck" }
            - { entity: Livraison, icon: "dolly" }

        brand_color: 'black'
    site_name: '<img src="/build/images/BrandHorizontalBlack.png" height="35"> ____Manager' 
    user:
        name_property_path: email # affichage en haut à droite de l'admin une fois la partie register faite
    entities:
        Utilisateurs:
            class: App\Entity\User
            list:
                actions:
                    - { name: 'edit', icon: 'edit', label: false, css_class: 'btn-secondary text-dark' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn-secondary text-danger' }
                fields:
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: lastname, label: 'Nom' }                    
                    - email
                    - { property: gender, label: 'Genre' }
                    - { property: address, label: 'Adresse' }
                    - { property: town, label: 'Ville' }
                    - { property: zipcode, label: 'Code Postal' }
                    - { property: country, label: 'Pays' }
                    - { property: phone_number, label: 'Téléphone' }
                    - { property: 'birthday', label: 'Date de Naissance' }                
                    
            form:
                fields: 
                    - { property: firstname, label: 'Prénom' }
                    - { property: lastname, label: 'Nom' }                    
                    - email
                    - { property: gender, label: 'Genre', type: choice, type_options: {choices: { 'femme' : '0', 'homme' : '1'}} }
                    - { property: address, label: 'Adresse' }
                    - { property: town, label: 'Ville' }
                    - { property: zipcode, label: 'Code Postal' }
                    - { property: country, label: 'Pays' }
                    - { property: phone_number, label: 'Téléphone' }
                    - { property: 'birthday', type: 'birthday', label: 'Date de Naissance' }
                    - roles
                    
            new:
                form_options: {validation_groups: ['registration']}
                fields:
                    - { property: plainPassword, type: 'password', label: 'Mot de passe' }

        Montres:
            class: App\Entity\WatchModel
            list:
                actions:
                    - { name: 'edit', icon: 'edit', label: false, css_class: 'btn-secondary text-dark' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn-secondary text-danger' }
                fields:
                    - { property: brand, label: 'Marque' }
                    - { property: model, label: 'Modèle' }
                    - { property: gender, label: 'Genre'}
                    - { property: color, label: 'Couleur' }
                    - { property: price, label: 'Prix' }
                    - { property: glass, label: 'Verre' }                    
                    - { property: movement, label: 'Mouvement' }
                    - { property: diameter, label: 'Diamètre' }
                    - { property: waterproof, label: 'Étanchéité' }
                    - { property: function, label: 'Fonction' }
                    - { property: watch_clasps, label: 'Fermoir' }
                    - Bracelet
                    - { property: watch_dial, label: 'Cadran' }
                    - { property: deposit, label: 'Caution' }
                    - { property: watchEntities, label: 'En Stock' }
            form:
                fields:
                    - { property: brand, label: 'Marque' }
                    - { property: model, label: 'Modèle' }
                    - { property: gender, label: 'Genre', type: choice, type_options: {choices: { 'femme' : '0', 'homme' : '1', 'unisex' : '2'}} }
                    - { property: description, label: 'Description' }
                    - { property: color, label: 'Couleur' }
                    - { property: price, label: 'Prix' }
                    - { property: glass, label: 'Verre' }                    
                    - { property: movement, label: 'Mouvement' }
                    - { property: diameter, label: 'Diamètre' }
                    - { property: waterproof, label: 'Étanchéité' }
                    - { property: function, label: 'Fonction' }
                    - { property: watch_clasps, label: 'Fermoir' }
                    - Bracelet
                    - { property: watch_dial, label: 'Cadran' }
                    - { property: deposit, label: 'Caution' }                   
                    - { property: pictures, type: 'collection', type_options: { entry_type: App\Form\PicturesType, allow_delete: true } }
                    - { property: watchEntities, label: 'Numéro de Série', type: 'collection', type_options: { entry_type: App\Form\EntityType, allow_delete: true} }
                    
        
        Numéro_de_série:
            class: App\Entity\WatchEntity
            disabled_actions: ['new']
            list:
                actions:
                    - { name: 'edit', icon: 'edit', label: false, css_class: 'btn-secondary text-dark' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn-secondary text-danger' }
                fields:
                    - { property: serial_number, label: 'Numéro de Série' }
                    - { property: watch_model, label: 'Modèle de montre' }
                    - { property: available, label: 'Status', type: 'toggle' }
            form:
                fields:
                    - { property: available, label: 'Status', type: 'toggle' }           


        Location:
            class: App\Entity\Location
            disabled_actions: ['new']
            list:
                actions:
                    - { name: 'edit', icon: 'edit', label: false, css_class: 'btn-secondary text-dark' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn-secondary text-danger' }
                filters: [{ property: 'ends_at', type: 'datetime' }]
                fields:
                    - { property: watch_entity, label: 'Numéro de Série' }
                    - { property: user, label: 'Client' }
                    - { property: location_number, label: 'Numéro de Location' }
                    - { property: starts_at, label: 'Début de Location' }
                    - { property: ends_at, label: 'Fin de Location' }
                    - { property: amount, label: 'Prix Total' }
                    - { property: is_paid, label: 'Status', type: 'toggle' }
                    - { property: bill_number, label: 'Numéro de Facture' }
            form:
                fields:
                    - { property: watch_entity, label: 'Numéro de Série' }
                    - { property: is_paid, label: 'Status' }

        Transporteurs:
            class: App\Entity\DeliveryCompany
            disabled_actions: ['edit']
            list:
                actions:
                    - { name: 'edit', icon: 'edit', label: false, css_class: 'btn-secondary text-dark' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn-secondary text-danger' }
                fields:
                    - { property: name, label: 'Nom' }
                    - logo
                    - { property: tracking_link, label: 'Lien de suivi' }
                    
                    
            form:
                fields:
                    - { property: name, label: 'Nom' }
                    - { property: logo, label: 'Logo', type: file_upload, type_options: { upload_dir: 'public/uploads'} }                    
                    - { property: tracking_link, label: 'Suivi de commande' }
        Livraison:
            class: App\Entity\Delivery
            disabled_actions: ['new']
            list:
                actions:
                    - { name: 'edit', icon: 'edit', label: false, css_class: 'btn-secondary text-dark' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn-secondary text-danger' }
                fields:
                    - { property: delivery_company, label: 'Transporteur' }
                    - { property: tracking_number, label: 'Numéro de suivi' }
                    - { property: address, label: 'Adresse' }
                    - { property: town, label: 'Ville' }
                    - { property: zipcode, label: 'Code Postal' }
                    - { property: country, label: 'Pays' }
                    - { property: returned_at, label: 'Date de Retour' }
            form:
                fields:
                    - { property: tracking_number, label: 'Numéro de suivi' }
                    - { property: address, label: 'Adresse' }
                    - { property: town, label: 'Ville' }
                    - { property: zipcode, label: 'Code Postal' }
                    - { property: country, label: 'Pays' }
                    - { property: returned_at, label: 'Date de Retour' }
                

