framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

 #           App\Entity\User:
 #               properties:
 #                   new:
 #                   password:
#                        - NotBlank: { groups: [registration] }
#                        - Length: { min: 6, max: 16, minMessage: Le mot de passe doit comporter au minimum {{ limit }} caractères, maxMessage: Le mot de passe doit comporter au maximum {{ limit }} caractères, groups: [registration] }
 
